import Head from "next/head";
import styles from "@/styles/index.module.css";
import Link from "next/link";
import { Contents } from "@/components/data";
import MyHeader from "@/components/MyHeader";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MyHeader/>
        <h1 className={styles.main_h1}>Contents</h1>
        <div className={styles.main_container}>
          {Contents.map((item,index)=>(
            <Link href={"./"+item.id} key={index}>
              <div className={styles.main_container_content} style={{backgroundColor:item.mainColor}}>
                {item.name}
              </div>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
